### ISSUE TITLE
Add option to disable Hitbox and Killaura checks for mobs, but keep them active for players

### ISSUE THREAD

**Issue by DimaSergeew** [Axionize/LightningGrim#1]
### Feature description

Hello,

I would like to request a new feature that allows disabling Hitbox and Killaura checks when the target is a mob. However, if the target is a player, these checks should still remain active, blocking and punishing illegal attacks.

This feature would be useful for servers where players use these types of mechanics for mob grinding or farming and skill leveling without penalizing them for fighting mobs.

Thank you for considering this suggestion!

**Comment by Axionize** [comment]
Noted, it may take a while to implement (not because it's difficult, just because I'm going to be very busy) but I'll get around to it.

I'd like to ask though, why do you want this feature? If its for performance that's perfectly understandable but unless there are false flags I'm unaware of this shouldn't penalize players when fighting mobs. If there are some false flags I'm unaware of please let me know, I'd like to prioritize fixing those.

**Comment by Axionize** [comment]
Hi, do you still want this feature. If so, why? Can you please tell me if it's for performance reasons or are there some falses being caused on mobs?

**Comment by DimaSergeew** [comment]
> Hi, do you still want this feature. If so, why? Can you please tell me if it's for performance reasons or are there some falses being caused on mobs?

On our server, cheats are permitted in PVE because we utilize an RPG system that demands a significant amount of mob grinding. Many players use KillAura to farm mobs while they are AFK or away from their computers. However, we strictly prohibit the use of KillAura in PVP!

Currently, the anti-cheat blocks all attacks on mobs, preventing players from farming them. It would be beneficial if the anti-cheat did not block hits when the target is a mob, but continued to block hits when the target is another player, ensuring that players using KillAura in PVP are penalized.

**Comment by ManInMyVan** [comment]
or the players could get better clients

**Comment by Axionize** [comment]
I see. That's a rather unique... use case but shouldn't be a problem I'll add a config option to `reach.ray_trace.ignore_mobs` or `player_only` for the reach check as soon as I have time. Hopefully in a few days.

**Comment by Axionize** [comment]
Done in B10
https://modrinth.com/plugin/lightning-grim-anticheat

Please re-open if it doesn't work or you still have an issue.

**Comment by Axionize** [comment]
Done in B10. The new option is `Reach.ignore-non-player-targets` which defaults to false and must be set to true.
https://modrinth.com/plugin/lightning-grim-anticheat

Please re-open if it doesn't work or you still have an issue.
