### ISSUE TITLE
Can all cheat detections be turned off?

### ISSUE THREAD

**Issue by 404forever1** [Axionize/LightningGrim#10]

**Comment by Axionize** [comment]
Yes, use the `grim.exempt` permission

**Comment by 404forever1** [comment]
> Yes, use the `grim.exempt` permission

Is there a detailed comparison wiki available?

**Comment by Axionize** [comment]
Its unneeded. if you're using luckperms you can exempt each individual check you want exempted with `grim.exempt.name-of-the-check`. The name of the check will autocomplete in Luckperms.

In addition you can edit punishments.yml to increase thresholds or reduce punishments.

The better question I'm asking though is what checks do you want to turn off and why? I would rather fix the issue with the check than having you exempt a broken check.

**Comment by Axionize** [comment]
I'm going to close this in a week and assume you no longer need my help if you don't reply.

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/c941b1e5-c3dc-436d-bcc1-5c36354c08c3)
Sorry, I was too busy a while ago and didn't have time to update. I tested it today and gave this permission but it didn't seem to work.

**Comment by Axionize** [comment]
They have to rejoin the server for the permission to take effect OR you have to restart your server.

**Comment by 404forever1** [comment]
> They have to rejoin the server for the permission to take effect OR you have to restart your server.
solve

**Comment by 404forever1** [comment]
thankyou
