### ISSUE TITLE
Reach 

### ISSUE THREAD

**Issue by Dbbtop** [Axionize/LightningGrim#11]
### Describe the false positive and how to replicate it

🤡
https://mega.nz/file/a7J2wRxC#ieCZ-FOSH-qPJWYHW7RkBqgUCoOgPbb0BdN-yjYdvSk

### Grim version

latest

### Server version

1.19.4

### Client version

vanilla 1.19.4

### Plugins

grim, packetevents, LP

**Comment by lll-Death-lll** [comment]
Same issue happens on 1.21.3

**Comment by xDangles** [comment]
The same thing happens on my 1.21.1.

**Comment by Axionize** [comment]
Apologies, I've always treated this as a place to dump every change I make and get feedback as fast as possible.

I didn't realize how popular my fork was and I pushed new config options I didn't fully test. Setting `skip-block-check` and `skip-entity-check:` will fix this and I'll push out a fix in B29 immediately.

**Comment by Axionize** [comment]
Try b29 should be fixed
https://modrinth.com/plugin/lightning-grim-anticheat

Please reopen this issue if it is not or open a new issue if you find any more bugs!
