### ISSUE TITLE
Anti-Cheat Spam Issue with Plugin Build b28

### ISSUE THREAD

**Issue by DimaSergeew** [Axionize/LightningGrim#14]
### Describe the bug and how to replicate it

![image](https://github.com/user-attachments/assets/9589c730-1141-4760-9380-104a98bc8a15)
After updating to plugin build b28, the anti-cheat system heavily spams the chat, and I am unable to disable it using the /grim alerts command.
Update to plugin build b28.
Observe the anti-cheat messages spamming the chat.
Attempt to disable the spam using /grim alerts.

### Grim version

b28

### Server version

1.20.4 Paper

### Plugins

not required in this case

**Comment by Axionize** [comment]
Do you have `/grim verbose` on by accident?

Also abdulo is cheating lmao

**Comment by DimaSergeew** [comment]
> Do you have `/grim verbose` on by accident?
> 
> Also abdulo is cheating lmao

verbose off

**Comment by Axionize** [comment]
Maybe this is caused by when I added permissions to the plugin.yml. Do you have `/op` on the server instead of using permissions?

**Comment by Axionize** [comment]
Try b31 I think it might fix this. Please confirm if it does https://modrinth.com/plugin/lightning-grim-anticheat

**Comment by DimaSergeew** [comment]
> Try b31 I think it might fix this. Please confirm if it does https://modrinth.com/plugin/lightning-grim-anticheat

Okay, I'll check tomorrow.

**Comment by DimaSergeew** [comment]
> Try b31 I think it might fix this. Please confirm if it does https://modrinth.com/plugin/lightning-grim-anticheat

![image](https://github.com/user-attachments/assets/b01f64f4-059c-4530-844b-aaf899e2ce89)

The plugin constantly enables verbose mode on its own, and I have to disable it manually every time.

**Comment by Axionize** [comment]
Are you certain you don't have the `grim.verbose.enable-on-join` permission?
