### ISSUE TITLE
Error when hitting a player

### ISSUE THREAD

**Issue by DeJoin** [Axionize/LightningGrim#30]
### Stack trace

https://paste.gg/p/anonymous/5111b8690d934c29990b173824ba9144
Full log file

### How to replicate it if known

Video:
https://www.dropbox.com/scl/fi/2n639ak89pcmgwnjfi8az/GrimAC.mp4?rlkey=ouctzvh4vta2v6uw1ozrgdkkc&st=jidc8q0l&dl=0

### Grim version

2.3.69-b40

### Server version

ShieldSpigot == Paper 1.16.5

### Plugins

AbstractMenus, ACubelets, AnimatedScoreboard, BAirDropX, BAuction, BLib, BottledExp, Chunky, ChunkyBorder, CMI, CMILib, CraftEnhance, CrazyCrates, DecentHolograms, DeluxeMenus, EnchantsSquared, fairy-lib-plugin, GrimAC, KillerMoney*, LuckPerms, Multiverse-Core, MyCommand, MythicMobs, OvRandomTeleport, packetevents, PlaceholderAPI, PlayerPoints, ProtocolLib, raytraced-antixray, ReActions, SCore, TerraformGenerator, Vault, ViaVersion, ViewDistanceTweaks, Vulcan, WorldEdit, WorldGuard, ZNPCsPlus

**Comment by Axionize** [comment]
I just fixed this In B41 please tell me if this fixed your issue.

https://modrinth.com/plugin/lightning-grim-anticheat

**Comment by DeJoin** [comment]
Yes, thank's
