### ISSUE TITLE
Server timeout and console spam

### ISSUE THREAD

**Issue by DeJoin** [Axionize/LightningGrim#31]
### Stack trace

https://paste.gg/p/anonymous/66c01b46bd4d4d86bddc5d5925527d48

### How to replicate it if known

It happens - when I go to the server, it doesn't let me in - there is an eternal connection, the second time I try to connect - the same situation.
After which the anti-cheat starts spamming incessantly in the console
To let me into the server and stop spamming the console, I need to reboot the server

### Grim version

2.3.69-b41

### Server version

ShieldSpigot = Paper 1.16.5

### Plugins

AbstractMenus, ACubelets, AnimatedScoreboard, BAirDropX, BAuction, BLib, BottledExp, Chunky, CMI, CMILib, CraftEnhance, CrazyCrates, DecentHolograms, DeluxeMenus, EnchantsSquared, fairy-lib-plugin, GrimAC, KillerMoney*, LuckPerms, Multiverse-Core, MyCommand, MythicMobs, OvRandomTeleport, packetevents, PlaceholderAPI, PlayerPoints, ProtocolLib, raytraced-antixray, TerraformGenerator, Vault, ViaVersion, ViewDistanceTweaks, Vulcan, WorldEdit, WorldGuard, ZNPCsPlus

**Comment by DeJoin** [comment]
Video:
https://www.dropbox.com/scl/fi/6vqqcdyz9lv5mhklnek8k/GrimAC2.mp4?rlkey=a54fofihzidd5gy1kr22jy95d&st=qfuc4irl&dl=0

I intentionally disconnect before logging into the server - and something weird happens.

**Comment by DeJoin** [comment]
Now I tried to remove AntiCheat - and this problem with the timeout is gone, that is, it lets me into the server without any problems even if I specifically cancelled the login before.

**Comment by Axionize** [comment]
This looks like an issue with your setup, are you running via on a proxy by some chance or do your other plugins screw with logging in logging out or packets in general?

Can you reproduce this on a clean server with Grim as the only plugin, and are you certain that if this issue does exist, its only in LightningGrim and not in Grim upstream?

I am 99% sure this issue is not the fault of LightningGrim.

**Comment by CodeJumper** [comment]
By disabling plugins one by one I found out that the problem appears when the DecentHolograms plugin is enabled
Is it impossible to solve?

**Comment by DeJoin** [comment]
I came to the conclusion that the problem occurs when Grim and ZNPCsPLUS are enabled together.
If I remove ZNPCsPLUS - everything is fine
If I remove Grim and leave ZNPCsPLUS - everything is fine too.
Is it possible to fix this or should I look for an alternative to ZNPCsPLUS?

**Comment by Axionize** [comment]
You may have to, but I would advise you to open an issue with ZNPCsPLUS to try and get to the bottom of the issue and see if it can be fixed
