### ISSUE TITLE
Reach false positive

### ISSUE THREAD

**Issue by murkjava** [Axionize/LightningGrim#32]
### Describe the false positive and how to replicate it

players on my server noticed false complaints for reach, to get them you need to:
1. throw debuff on the opponent (in my case was slowing, drying well and little things)
2. drink speed 2
3. run after the player and hit (not always the first time) and complains for false reach, I checked and this in the original is not there

### Grim version

631217a

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Client version

1.21

### Plugins

only this grim fork and his dependencies (local server)

**Comment by murkjava** [comment]
> ### Describe the false positive and how to replicate it
> players on my server noticed false complaints for reach, to get them you need to:
> 
> 1. throw debuff on the opponent (in my case was slowing, drying well and little things)
> 2. drink speed 2
> 3. run after the player and hit (not always the first time) and complains for false reach, I checked and this in the original is not there
> 
> ### Grim version
> [631217a](https://github.com/Axionize/LightningGrim/commit/631217a7f4e319a65db03a71215e1c890c61ec79)
> 
> ### Server version
> This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
> 
> ### Client version
> 1.21
> 
> ### Plugins
> only this grim fork and his dependencies (local server)

i tested on local (with friend) and this work

**Comment by Axionize** [comment]
I broke this in B38, Should be fixed in B44
https://modrinth.com/plugin/lightning-grim-anticheat

**Comment by murkjava** [comment]
thanks
