### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by DimaSergeew** [Axionize/LightningGrim#7]
### Describe the bug and how to replicate it

https://mclo.gs/doNUCgS - spam console

### Grim version

Lightning Grim Anticheat 2.3.69-b12

### Server version

purpur 1.20.4

### Plugins

-

**Comment by overkidding** [comment]
@Axionize Line 194 of BlockRayTrace

**Comment by asygamesperson** [comment]
Also i get this error in console: https://paste.helpch.at/kasetelofi.css

**Comment by Axionize** [comment]
@DimaSergeew @overkidding  Forgot to remove my debug statements while testing. Will fix.

@asygamesperson ah I was worried that would happen but it didn't come up in testing. Should only happen if a ComplexCollisionBox is made up of another ComplexCollisionBox, which should never happen they should always be made up of SimpleCollisionBoxes. Do you know what you were doing/what block triggered that error? I can fix it by unoptimizing the code to use the old CollisionBox behaviour but I'd rather fix it by fixing the block modeling.

**Comment by asygamesperson** [comment]
I am not sure, I am seeing that random in console

**Comment by Axionize** [comment]
@asygamesperson @DimaSergeew @asygamesperson Fixed in B14. Please tell me if you find any more issues.
