### ISSUE TITLE
Folia 1.21.1 - Error log in console

### ISSUE THREAD

**Issue by NeoFolia** [Axionize/LightningGrim#8]
### Stack trace

[latest.log](https://github.com/user-attachments/files/17815532/latest.log)

### Grim version

grimac-2.3.69-b14.jar

### Server version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-18T16:35:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### Plugins

![image](https://github.com/user-attachments/assets/cb31ab80-cfde-4d26-8b45-83e7b74411ac)

**Comment by overkidding** [comment]
Just wait that they merge the folia error fixes

**Comment by Axionize** [comment]
Duplicate of #6. Should be fixed in B15 https://modrinth.com/plugin/lightning-grim-anticheat
